---
##########################
##########################
## TemplateBot issueOps ##
##########################
##########################
name: TemplateBot IssueOps

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#################
# Start the job #
#################
on:
  pull_request:
    types: [edited]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: IssueOPs
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ############################
      # Checkout users code base #
      ############################
      - name: Checkout Users Code
        uses: actions/checkout@v2

      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout TemplateBot Code
        uses: actions/checkout@v2
        with:
          repository: lukaspersonal/templatebotrepo
          path: templatebotrepo

      ##############################################################
      # Run the templatebot script to apply template to repository #
      ##############################################################
      - name: Run TemplateBot
        run: ./.automation/apply-template.sh
