---
#############################################
# TemplateBot workflow to find repositories #
# and insert templates                      #
#############################################
name: TemplateBot

#################################################
# Set to run on schedule or on just random runs #
#################################################
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Un-comment to run on schedule default every 2 hrs
  # schedule:
  #   - cron: '0 */2 * * *'

###############
# Set the Job #
###############
jobs:
  TemplateBot:
    runs-on: ubuntu-latest
    steps:
      ####################################################################
      # generate a token that gives us access to all repositories in org #
      ####################################################################
      - name: Generate Token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID }}

      ##################################################
      # Checks-out TemplateBot under $GITHUB_WORKSPACE #
      ##################################################
      - name: Checkout TemplateBot
        uses: actions/checkout@v2

      #######################
      # Run the TemplateBot #
      #######################
      - name: Find and Add Templates
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
        run: ./.automation/template-the-world.sh
